apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-app-replica-set
  labels:
    type: front-end
    name: myapp
spec:
  template:
    metadata:
      name: my-app
      labels:
        type: front-end
    spec:
      containers:
        - name: mongo
          image: mongo
  replicas: 3
  selector:
    matchLabels:
      type: front-end
