apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
    tier: front-end
spec:
  template:
    metadata:
      name: my-app
      labels:
        tier: front-end
        app: my-app
    spec:
      containers:
        - image:  nginx
          name:  my-nginx-container
  replicas: 4
  selector:
    matchLabels:
      tier: front-end
