apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: my-app
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-second-container
          image: nginx
  replicas: 7
  selector:
    matchLabels:
      type: front-end